create table if not exists public.ai_tool_audit_logs (
  id bigint generated by default as identity primary key,
  actor_uid uuid not null default auth.uid(),
  tool_name text not null,
  result text not null check (result in ('success','failed','denied','confirmation_required','cancelled')),
  confirmed boolean not null default false,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.ai_tool_audit_logs enable row level security;

drop policy if exists ai_tool_audit_logs_insert_own on public.ai_tool_audit_logs;
create policy ai_tool_audit_logs_insert_own on public.ai_tool_audit_logs
for insert to authenticated
with check (actor_uid = (select auth.uid()));

drop policy if exists ai_tool_audit_logs_staff_read on public.ai_tool_audit_logs;
create policy ai_tool_audit_logs_staff_read on public.ai_tool_audit_logs
for select to authenticated
using (
  actor_uid = (select auth.uid())
  or coalesce((select auth.jwt()->>'app_role'),'') = any(array['admin','owner','developer'])
  or coalesce(((select auth.jwt()->>'admin'))::boolean,false)
  or coalesce(((select auth.jwt()->>'owner'))::boolean,false)
  or coalesce(((select auth.jwt()->>'developer'))::boolean,false)
);

create index if not exists ai_tool_audit_logs_actor_created_idx on public.ai_tool_audit_logs(actor_uid, created_at desc);
create index if not exists ai_tool_audit_logs_tool_created_idx on public.ai_tool_audit_logs(tool_name, created_at desc);
