-- Alfaeq Yemen: Jev typed-decision audit layer.
-- Jev assesses; deterministic Alfaeq code remains the final executor.

create table if not exists public.ai_jev_decisions (
  id bigint generated by default as identity primary key,
  event_id text,
  event_type text not null,
  decision_pack text not null,
  model text,
  source text not null default 'jev' check (source in ('jev','fallback')),
  latency_ms integer,
  answers jsonb not null default '{}'::jsonb,
  input_fingerprint text,
  created_at timestamptz not null default now()
);

create index if not exists ai_jev_decisions_event_idx
  on public.ai_jev_decisions(event_id, created_at desc);

create index if not exists ai_jev_decisions_created_idx
  on public.ai_jev_decisions(created_at desc);

alter table public.ai_jev_decisions enable row level security;

-- Decisions are written by Edge Functions with service_role.
-- No direct client INSERT/UPDATE/DELETE is granted.
drop policy if exists "ai_jev_decisions_read_staff" on public.ai_jev_decisions;
create policy "ai_jev_decisions_read_staff"
on public.ai_jev_decisions
for select
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.uid = auth.uid()
      and (
        lower(coalesce(u.role, '')) in ('owner','admin','developer')
        or coalesce(u.owner, false) = true
        or coalesce(u.admin, false) = true
        or coalesce(u.developer, false) = true
      )
  )
);
