-- Alfaeq Yemen AI Control Plane
-- Inspired by Paperclip control-plane concepts.
create table if not exists public.ai_agents (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  role text not null,
  manager_id uuid references public.ai_agents(id) on delete set null,
  capabilities text[] not null default '{}',
  adapter_type text not null default 'http',
  adapter_config jsonb not null default '{}'::jsonb,
  status text not null default 'idle' check (status in ('active','idle','running','error','paused','terminated')),
  budget_monthly_cents bigint not null default 0 check (budget_monthly_cents >= 0),
  spend_monthly_cents bigint not null default 0 check (spend_monthly_cents >= 0),
  heartbeat_interval_minutes integer not null default 60 check (heartbeat_interval_minutes > 0),
  last_heartbeat_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.ai_tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  status text not null default 'backlog' check (status in ('backlog','todo','in_progress','in_review','done','blocked','cancelled')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assignee_id uuid references public.ai_agents(id) on delete set null,
  parent_task_id uuid references public.ai_tasks(id) on delete set null,
  project_key text,
  goal_key text,
  checkout_token uuid,
  checked_out_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.ai_activity_log (
  id bigint generated by default as identity primary key,
  agent_id uuid references public.ai_agents(id) on delete set null,
  task_id uuid references public.ai_tasks(id) on delete set null,
  event_type text not null,
  provider text,
  model text,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  cost_cents bigint not null default 0,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists ai_agents_manager_idx on public.ai_agents(manager_id);
create index if not exists ai_agents_status_idx on public.ai_agents(status);
create index if not exists ai_tasks_status_idx on public.ai_tasks(status);
create index if not exists ai_tasks_assignee_idx on public.ai_tasks(assignee_id);
create index if not exists ai_activity_agent_created_idx on public.ai_activity_log(agent_id, created_at desc);
create index if not exists ai_activity_task_created_idx on public.ai_activity_log(task_id, created_at desc);
alter table public.ai_agents enable row level security;
alter table public.ai_tasks enable row level security;
alter table public.ai_activity_log enable row level security;
drop policy if exists "ai_agents_read_authenticated" on public.ai_agents;
create policy "ai_agents_read_authenticated" on public.ai_agents for select to authenticated using (true);
drop policy if exists "ai_tasks_read_authenticated" on public.ai_tasks;
create policy "ai_tasks_read_authenticated" on public.ai_tasks for select to authenticated using (true);
drop policy if exists "ai_activity_read_authenticated" on public.ai_activity_log;
create policy "ai_activity_read_authenticated" on public.ai_activity_log for select to authenticated using (true);

create unique index if not exists ai_tasks_event_id_unique
  on public.ai_tasks ((metadata->>'event_id'))
  where metadata->>'event_id' is not null;

-- Seed the initial AI organization hierarchy idempotently.
insert into public.ai_agents (name, role, capabilities, adapter_type, status)
select 'Alfaeq AI CEO', 'CEO', array['strategy','delegation','governance'], 'http', 'idle'
where not exists (select 1 from public.ai_agents where name = 'Alfaeq AI CEO');

insert into public.ai_agents (name, role, manager_id, capabilities, adapter_type, status)
select 'Alfaeq CTO', 'CTO', id, array['engineering','architecture','security'], 'http', 'idle'
from public.ai_agents where name = 'Alfaeq AI CEO'
and not exists (select 1 from public.ai_agents where name = 'Alfaeq CTO');

insert into public.ai_agents (name, role, manager_id, capabilities, adapter_type, status)
select 'Alfaeq Operations', 'Operations', id, array['orders','dispatch','merchant','operations'], 'http', 'idle'
from public.ai_agents where name = 'Alfaeq AI CEO'
and not exists (select 1 from public.ai_agents where name = 'Alfaeq Operations');

insert into public.ai_agents (name, role, manager_id, capabilities, adapter_type, status)
select 'Alfaeq Marketing', 'Marketing', id, array['marketing','promotion','content'], 'http', 'idle'
from public.ai_agents where name = 'Alfaeq AI CEO'
and not exists (select 1 from public.ai_agents where name = 'Alfaeq Marketing');

insert into public.ai_agents (name, role, manager_id, capabilities, adapter_type, status)
select 'Alfaeq Automation', 'Automation', id, array['automation','n8n','integrations'], 'http', 'idle'
from public.ai_agents where name = 'Alfaeq CTO'
and not exists (select 1 from public.ai_agents where name = 'Alfaeq Automation');
