-- Alfaeq Yemen: Jev typed-decision audit layer.
create table if not exists public.ai_jev_decisions (
  id bigint generated by default as identity primary key,
  event_id text,
  event_type text not null,
  decision_pack text not null,
  model text,
  source text not null default 'jev' check (source in ('jev','fallback')),
  latency_ms integer,
  answers jsonb not null default '{}'::jsonb,
  input_fingerprint text,
  created_at timestamptz not null default now()
);
create index if not exists ai_jev_decisions_event_idx
  on public.ai_jev_decisions(event_id, created_at desc);
create index if not exists ai_jev_decisions_created_idx
  on public.ai_jev_decisions(created_at desc);
alter table public.ai_jev_decisions enable row level security;
